
name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    
jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.rust == 'nightly' }}
    strategy:
      matrix:
        rust: [beta, nightly]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Install rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          profile: minimal
          override: true

      - name: Install Souffle
        run: |
          wget https://github.com/ecstatic-morse/souffle/releases/download/2.0.2-alpha/souffle-2.0.2-Linux.deb
          sudo apt install ./souffle-2.0.2-Linux.deb

      - name: Execute tests
        run: cargo test
